version: 0.0
os: linux
files:
- source: /target/aws-sample.war
  destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  BeforeInstall:
  - location: scripts/install_dependencies
    timeout: 300
  ApplicationStart:
  - location: scripts/write_codedeploy_config.sh
  - location: scripts/start_application
    timeout: 300
  ValidateService:
  - location: scripts/basic_health_check.sh
